package ast

const(
	SIZE string = "SIZE"
	PATH string = "PATH"
	FIT string = "FIT"
	UNIT string = "UNIT"
	NAME string = "NAME"
	USUARIO string = "USUARIO"
	GRP string = "GRP"
	PASSWORD string = "PASSWORD"
	PWD string = "PWD"
	TYPE string = "TYPE"
	ID string = "ID"
	CONT string = "CONT"
	RUTA string = "RUTA"
	P string = "P"
	R string = "R"
	FF string = "FF"
	BF string = "BF"
	WF string = "WF"
	PP string = "P"
	L string = "L"
	E string = "E"
	FAST string = "FAST"
	FULL string = "FULL"
	M string = "M"
	K string = "K"
	B string = "B"
)